name: super_resolutions_using_efficient_sub_pixel_cnn
dataset_url: https://www2.eecs.berkeley.edu/Research/Projects/CS/vision/grouping/BSR/BSR_bsds500.tgz
crop_size: 300
upscale_factor: 3
validation_split: 0.2
batch_size: 8
conv_activation: relu
conv_kernel_initializer: orthogonal
conv_padding: same
hidden_units: 64
hidden_layers: 3
kernel_size:
  decoder: 5
  encoder: 3
channels: 1
epochs: 100
lr: 0.001



checkpoint_save_epoch: 5
buffer_size: 35000
image_size: !!python/tuple [64, 64, 3]
unit: 64
generator_layer_iterator: 3
discriminator_layer_iterator: 4
generator_stride:
  - 1
  - 2
  - 2
  - 2
discriminator_stride: 2
kernel: 5
dropout_ratio: 0.3
lr_generator: !!float 1e-4
lr_discriminator: !!float  1e-4
noise_dimension: 100
num_example_to_generate: 1
