name: super_resolutions_using_efficient_sub_pixel_cnn
dataset_url: https://www2.eecs.berkeley.edu/Research/Projects/CS/vision/grouping/BSR/BSR_bsds500.tgz
crop_size: 300
upscale_factor: 3
validation_split: 0.2
batch_size: 8
conv_activation: relu
conv_kernel_initializer: orthogonal
conv_padding: same
hidden_units: 64
hidden_layers: 3
kernel_size:
  decoder: 5
  encoder: 3
channels: 1
epochs: 100
lr: 0.001
